# Generated by Django 5.0.1 on 2024-01-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0002_rename_user_userregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
